MODEL:
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  MEMORY_MOMENTUM: 0.2
  ID_LOSS_WEIGHT: 0.25
  PCL_LOSS_WEIGHT: 1.0
  # SIE_CAMERA: True
  # SIE_COE : 1.0

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
 
DATALOADER:
  NUM_INSTANCE: 8
  NUM_WORKERS: 8
  NUM_ITERS: 300

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "AdamW"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 180
    CHECKPOINT_PERIOD: 180
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5
#  GLOBAL_BATCH: 256
  IMS_PER_BATCH: 64
  OPTIMIZER_NAME: "SGD"
  BASE_LR: 3.5e-4
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 5.0e-4
  MAX_EPOCHS: 40
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 5
  ITERS: 200
  K1: 30
  
  STEPS: [30, 50]
  GAMMA: 0.1
  
TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False

DATASETS:
  NAMES: ('dnwild') #dn348, wild
  ROOT_DIR: ('../../dataset/dn_reid/')
OUTPUT_DIR: './output_logs_wild'