MODEL:
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  MEMORY_MOMENTUM: 0.2

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATALOADER:
  NUM_INSTANCE: 8
  NUM_WORKERS: 8
  NUM_ITERS: 300

SOLVER:
  IMS_PER_BATCH: 64
  OPTIMIZER_NAME: 'SGD'
  BASE_LR: 0.00035
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  MAX_EPOCHS: 40
  STEPS: [30, 50]
  GAMMA: 0.1
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  LOG_PERIOD: 50
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 10
  K1: 30

BASELINE:
  CLUSTER_EPS: 0.6
  CLUSTER_MIN_SAMPLES: 4
  JACCARD_K2: 6
  PCL_TEMP: 0.05
  PCL_HARD_MEMORY: True
  EVAL_TRIALS: 10

TEST:
  IMS_PER_BATCH: 64
  FEAT_NORM: 'yes'
  RE_RANKING: False

DATASETS:
  NAMES: 'SYSU-MM01'
  ROOT_DIR: '../../dataset/VI-ReID'

OUTPUT_DIR: './output_logs_sysu_baseline'
